---
- name: check if rabbitmq is running
  shell: "service rabbitmq-server status"
  args:
    warn: false # cannot check status with service module
  register: rabbitmq_status
  failed_when: false
  changed_when: false

- name: install rabbitmq plugin
  apt:
    pkg=sd-agent-rabbitmq
    update_cache=true
  notify:
    - restart sd_agent
  when: rabbitmq_status.rc == 0

- name: set rabbitmq plugin configuration
  copy:
    src=rabbitmq.yaml
    dest=/etc/sd-agent/conf.d/rabbitmq.yaml
  notify:
    - restart sd_agent
  when: rabbitmq_status.rc == 0
