---
- name: check if mongo is running
  shell: "service mongod status"
  args:
    warn: false # cannot check status with service module
  register: mongo_status
  failed_when: false
  changed_when: false

- name: install mongodb plugin
  apt:
    pkg=sd-agent-mongo
    update_cache=true
  notify:
    - restart sd_agent
  when: mongo_status.rc == 0

- name: set mongo plugin configuration
  copy:
    src=mongo.yaml
    dest=/etc/sd-agent/conf.d/mongo.yaml
  notify:
    - restart sd_agent
  when: mongo_status.rc == 0
